version: "3.8"

services:
    database:
        image: postgres
        container_name: database_xlsolution
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=hiring
            - POSTGRES_DB=hiring
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: app_xlsolution
        ports:
            - 5000:5000
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database


volumes:
    pgdata:
        driver: local