[default]
SECRET_KEY = 'Desenvolvedor Python'
SQLALCHEMY_DATABASE_URI = 'postgresql://docker:xlsolution@database/xlsolution'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    'app.resources:init_app',
    'app.db:init_app'
]